sportsbooks:
  - sbid: 1157
    paid: 63
    nam: 10Bet

  - sbid: 1625
    paid: 66
    nam: 1Vice

  - sbid: 19
    paid: 3
    nam: 5Dimes

  - sbid: 1439
    paid: 40
    nam: 888Sport

  - sbid: 43
    paid: 5
    nam: Bet365

  - sbid: 45
    paid: 74
    nam: BetAtHome

  - sbid: 1601
    paid: 75
    nam: BetClic

  - sbid: 1279
    paid: 86
    nam: BetFred

  - sbid: 1096
    paid: 8
    nam: BetOnline

  - sbid: 1274
    paid: 71
    nam: BetWay

  - sbid: 92
    paid: 9
    nam: Bodog Sportsbook

  - sbid: 93
    paid: 10
    nam: Bookmaker

  - sbid: 1618
    paid: 9
    nam: Bovada

  - sbid: 1696
    paid: 93
    nam: Cloudbet

  - sbid: 394
    paid: 77
    nam: Coral

  - sbid: 1602
    paid: 65
    nam: GTbets

  - sbid: 1681
    paid: 80
    nam: Guts

  - sbid: 169
    paid: 44
    nam: Heritage Sports

  - sbid: 180
    paid: 29
    nam: Intertops

  - sbid: 182
    paid: 73
    nam: Interwetten

  - sbid: 1275
    paid: 16
    nam: JustBet

  - sbid: 192
    paid: 43
    nam: Ladbrokes

  - sbid: 626
    paid: 18
    nam: Matchbook

  - sbid: 238
    paid: 20
    nam: Pinnacle

  - sbid: 1611
    paid: 52
    nam: SBOBet

  - sbid: 274
    paid: 84
    nam: Skybook

  - sbid: 283
    paid: 68
    nam: SportingBet

  - sbid: 289
    paid: 8
    nam: SportsBetting

  - sbid: 1137
    paid: 81
    nam: StanJames

  - sbid: 227
    paid: 22
    nam: The Greek Sportsbook

  - sbid: 1567
    paid: 57
    nam: TitanBet

  - sbid: 1459
    paid: 76
    nam: Unibet

  - sbid: 349
    paid: 36
    nam: William Hill

  - sbid: 1673
    paid: 69
    nam: Winner.com
