version: 2.1

jobs:
  build:
    # code runs inside this docker image, using python 3.9
    docker:
      - image: circleci/python:3.8.6

    # this is the default value
    working_directory: ~/project

    steps:
      # get code from Github
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev

      - run:
          name: run tests
          command: |
            pipenv run flake8
            pipenv run pytest -v --cov pysbr
